language: python
python:
  - "3.7"
install:

  - "pip install pycodestyle"
  - "pip install -e ."

# command to run tests
script:
  # Tests

  - python setup.py test
  - pycodestyle pythontabcmd2 tests
  - pytest