name: Publish to PyPi


# TODO: actually plan when we want to trigger this job
# maybe move it into the package job so all release-based actions are together
#  - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
on:
  workflow_dispatch:
    inputs:
      is_draft:
        description: 'Test PyPi'
        required: true
        type: boolean
  push:
    branches: development, main

jobs:
  build-n-publish:
    name: Build dist files for PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Build dist files
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          python setup.py sdist --formats=gztar
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1  # license BSD-2
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: ${{ github.ref == 'refs/heads/master' && inputs.is_draft }}
        uses: pypa/gh-action-pypi-publish@release/v1  # license BSD-2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

